### ISSUE TITLE
About xlsx data file problem

### ISSUE THREAD

**Issue by baidu2018** [msunij/EV_DemandSimulation#1]
Hello! When I was looking at the project, I found that the files "output_template.xlsx" and "demand_output_single_connection" were not found. Do you still have data? Thank you

**Comment by msunij** [comment]
Hello,
Yes, I have them with me.
"output_single_connection.txt" should be generated by the code, I'm attaching what I've generated previously.
[output_single_connection.txt](https://github.com/msunij/EV_DemandSimulation/files/5080313/output_single_connection.txt)
[output_template.xlsx](https://github.com/msunij/EV_DemandSimulation/files/5080315/output_template.xlsx)

**Comment by baidu2018** [comment]
Thank you very much for your help, I will go to learn, thank you very much!
